CREATE TABLE categories (
    category_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE companies (
    company_id INT AUTO_INCREMENT PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    company_logo VARCHAR(255)
);

CREATE TABLE jobs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    company_id INT,
    category_id INT,
    location VARCHAR(100),
    job_type ENUM('Full Time', 'Part Time', 'Temporary') NOT NULL,
    contract_type ENUM('Permanent', 'Contract', 'Temporary') NOT NULL,
    deadline DATE,
    description TEXT,
    apply_link VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(company_id),
    FOREIGN KEY (category_id) REFERENCES categories(category_id)
);

CREATE TABLE contacts (
    contact_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    message TEXT NOT NULL,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE subscriptions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sub_email VARCHAR(255) NOT NULL,
    date_subscribed TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO categories (name) VALUES 
('Accounting & Finance'),
('Admin & Management'),
('Creative & Design'),
('Construction & Architecture'),
('Customer Service & Support'),
('Engineering & Technology'),
('Farming & Agriculture'),
('Food Services & Catering'),
('Hospitality & Leisure'),
('IT & Software'),
('Legal Services'),
('Marketing & Communications'),
('Medical & Pharmaceutical'),
('Project Management'),
('Human Resources'),
('Community & Social Services'),
('Sales'),
('Supply Chain & Procurement'),
('Education'),
('Driver & Transport Services');

INSERT INTO companies (company_name, company_logo) VALUES 
('Uganda Revenue Authority', 'assets/images/companies/ura.png'),
('MTN Uganda', 'assets/images/companies/mtn.png'),
('Riham Uganda', 'assets/images/companies/riham.png'),
('National Social Security Fund', 'assets/images/companies/nssf.png'),
('Office of the President', 'assets/images/companies/statehouse.jpg'),
('Total Energies Uganda', 'assets/images/companies/total.png'),
('Uganda Breweries Limited', 'assets/images/companies/ubl.png'),
('Stanbic Bank Uganda', 'assets/images/companies/stanbic.png'),
('UMEME', 'assets/images/companies/umeme.png'),
('Uganda Wildlife Authority', 'assets/images/companies/uwu.png'),
('Uganda Communications Commission', 'assets/images/companies/ucc.png'),
('Uganda Airlines', 'assets/images/companies/uganda_airlines.png'),
('Coca-Cola Beverages Africa Uganda', 'assets/images/companies/coca_cola.png'),
('Uganda Police Force', 'assets/images/companies/uganda_police.png'),
('Cementers Uganda Limited', 'assets/images/companies/cementers.png'),
('Bank of Uganda', 'assets/images/companies/bou.png'),
('Uganda Civil Aviation Authority', 'assets/images/companies/uganda_caa.png'),
('Geothermal Uganda', 'assets/images/companies/geothermal.png'),
('Uganda Investment Authority', 'assets/images/companies/uia.png'),
('Uganda National Roads Authority', 'assets/images/companies/unra.png'),
('Barclays Bank Uganda', 'assets/images/companies/barclays.png'),
('East African Breweries Limited', 'assets/images/companies/eabl.png'),
('Lira Sugar Factory', 'assets/images/companies/lira_sugar.png'),
('Uganda Red Cross Society', 'assets/images/companies/uganda_red_cross.png'),
('Makerere University', 'assets/images/companies/makerere.png'),
('Uganda National Airlines', 'assets/images/companies/national_airlines.png'),
('DHL Express Uganda', 'assets/images/companies/dhl.png'),
('Uganda Cancer Institute', 'assets/images/companies/uganda_cancer.png'),
('UBC', 'assets/images/companies/ubc.png'),
('Uganda Bureau of Statistics', 'assets/images/companies/ubs.png'),
('MTN Group Limited', 'assets/images/companies/mtn_group.png'),
('Uganda Telecom Limited', 'assets/images/companies/uganda_telecom.png'),
('Shell Uganda', 'assets/images/companies/shell.png'),
('Centenary Bank', 'assets/images/companies/centenary_bank.png'),
('Uganda Petroleum Institute Kigumba', 'assets/images/companies/upi_kigumba.png'),
('Uganda Development Bank Limited', 'assets/images/companies/udbl.png'),
('Bata Uganda Limited', 'assets/images/companies/bata.png'),
('Mukwano Group of Companies', 'assets/images/companies/mukwano.png'),
('Uganda Post Limited', 'assets/images/companies/uganda_post.png'),
('Uganda Development Corporation', 'assets/images/companies/udc.png'),
('Nile Breweries Limited', 'assets/images/companies/nile_breweries.png'),
('Jumia Uganda', 'assets/images/companies/jumia.png'),
('Uganda Christian University', 'assets/images/companies/ucu.png'),
('Abacus Pharma Uganda', 'assets/images/companies/abacus_pharma.png'),
('Agriculture Technology Limited', 'assets/images/companies/agritech.png'),
('Kampala City Council Authority', 'assets/images/companies/kcca.png'),
('Uganda Communications Ltd', 'assets/images/companies/uganda_comms.png'),
('Uganda Investment Authority', 'assets/images/companies/invest_uganda.png'),
('Tullow Oil Uganda', 'assets/images/companies/tullow_oil.png'),
('Uganda Revenue Authority IT Department', 'assets/images/companies/ura_it.png'),
('Hilton Hotel Kampala', 'assets/images/companies/hilton_kampala.png'),
('U-Learn Uganda', 'assets/images/companies/ulearn.png'),
('Viscorp Technologies Uganda', 'assets/images/companies/viscorp.png'),
('Unilever Uganda Limited', 'assets/images/companies/unilever.png'),
('Uganda Wildlife Education Centre', 'assets/images/companies/uwec.png'),
('Uganda Heart Institute', 'assets/images/companies/heart_institute.png'),
('Food and Agriculture Organization', 'assets/images/companies/fao.png'),
('Eagle Air Uganda', 'assets/images/companies/eagle_air.png');

INSERT INTO jobs (title, company_id, category_id, location, job_type, contract_type, deadline, description, apply_link) VALUES
('Tax Consultant', 1, 1, 'Kampala', 'Full Time', 'Permanent', '2024-11-25', 'Tax Consultant at Uganda Revenue Authority', 'https://example.com/apply-for-tax-consultant'),
('Customer Support Officer', 2, 5, 'Kampala', 'Full Time', 'Permanent', '2024-12-05', 'Customer Support role at MTN Uganda', 'https://example.com/apply-for-customer-support'),
('Quality Assurance Specialist', 3, 3, 'Kampala', 'Full Time', 'Permanent', '2024-11-28', 'Quality Assurance Specialist at Riham Uganda', 'https://example.com/apply-for-quality-assurance'),
('Compliance Officer', 4, 1, 'Kampala', 'Full Time', 'Permanent', '2024-11-30', 'Compliance Officer at National Social Security Fund', 'https://example.com/apply-for-compliance-officer'),
('Office Administrator', 5, 2, 'Kampala', 'Full Time', 'Permanent', '2024-12-01', 'Office Administrator role at Office of the President', 'https://example.com/apply-for-office-administrator'),
('Field Engineer', 6, 6, 'Hoima', 'Full Time', 'Contract', '2024-12-10', 'Field Engineer at Total Energies Uganda', 'https://example.com/apply-for-field-engineer'),
('Marketing Coordinator', 7, 12, 'Kampala', 'Part Time', 'Temporary', '2024-12-15', 'Marketing role at Uganda Breweries Limited', 'https://example.com/apply-for-marketing-coordinator'),
('Bank Teller', 8, 1, 'Kampala', 'Full Time', 'Permanent', '2024-12-20', 'Bank Teller role at Stanbic Bank Uganda', 'https://example.com/apply-for-bank-teller'),
('Mechanical Engineer', 9, 6, 'Jinja', 'Full Time', 'Permanent', '2024-12-25', 'Mechanical Engineer role at UEGCL', 'https://example.com/apply-for-mechanical-engineer'),
('Tour Guide', 10, 16, 'Bwindi', 'Full Time', 'Permanent', '2024-11-30', 'Tour Guide role at Uganda Wildlife Authority', 'https://example.com/apply-for-tour-guide'),
('IT Specialist', 11, 10, 'Kampala', 'Full Time', 'Permanent', '2024-12-05', 'IT Specialist at Uganda Communications Commission', 'https://example.com/apply-for-it-specialist'),
('Flight Attendant', 12, 16, 'Entebbe', 'Full Time', 'Permanent', '2024-12-08', 'Flight Attendant role at Uganda Airlines', 'https://example.com/apply-for-flight-attendant'),
('Sales Representative', 13, 17, 'Kampala', 'Part Time', 'Temporary', '2024-12-10', 'Sales role at Coca-Cola Beverages Africa Uganda', 'https://example.com/apply-for-sales-representative'),
('Police Officer', 14, 16, 'Kampala', 'Full Time', 'Permanent', '2024-12-12', 'Police Officer role at Uganda Police Force', 'https://example.com/apply-for-police-officer'),
('Construction Manager', 15, 4, 'Kampala', 'Full Time', 'Permanent', '2024-12-15', 'Construction Manager at Cementers Uganda Limited', 'https://example.com/apply-for-construction-manager'),
('Financial Analyst', 16, 1, 'Kampala', 'Full Time', 'Permanent', '2024-12-18', 'Financial Analyst at Bank of Uganda', 'https://example.com/apply-for-financial-analyst'),
('Air Traffic Controller', 17, 10, 'Entebbe', 'Full Time', 'Permanent', '2024-12-20', 'Air Traffic Controller role at Uganda Civil Aviation Authority', 'https://example.com/apply-for-air-traffic-controller'),
('Geologist', 18, 6, 'Kasese', 'Full Time', 'Permanent', '2024-12-22', 'Geologist at Geothermal Uganda', 'https://example.com/apply-for-geologist'),
('Investment Analyst', 19, 1, 'Kampala', 'Full Time', 'Permanent', '2024-12-23', 'Investment Analyst role at Uganda Investment Authority', 'https://example.com/apply-for-investment-analyst'),
('Civil Engineer', 20, 6, 'Gulu', 'Full Time', 'Permanent', '2024-12-25', 'Civil Engineer role at Uganda National Roads Authority', 'https://example.com/apply-for-civil-engineer'),
('Branch Manager', 21, 1, 'Kampala', 'Full Time', 'Permanent', '2024-12-27', 'Branch Manager at Barclays Bank Uganda', 'https://example.com/apply-for-branch-manager'),
('Quality Inspector', 22, 6, 'Jinja', 'Full Time', 'Temporary', '2024-12-28', 'Quality Inspector at East African Breweries Limited', 'https://example.com/apply-for-quality-inspector'),
('Plant Operator', 23, 6, 'Lira', 'Full Time', 'Permanent', '2024-12-30', 'Plant Operator at Lira Sugar Factory', 'https://example.com/apply-for-plant-operator'),
('Logistics Coordinator', 24, 18, 'Kampala', 'Full Time', 'Permanent', '2024-12-31', 'Logistics Coordinator at Uganda Red Cross Society', 'https://example.com/apply-for-logistics-coordinator'),
('Research Assistant', 25, 19, 'Kampala', 'Full Time', 'Temporary', '2025-01-05', 'Research Assistant at Makerere University', 'https://example.com/apply-for-research-assistant'),
('Flight Crew', 26, 16, 'Entebbe', 'Full Time', 'Permanent', '2025-01-07', 'Flight Crew at Uganda National Airlines', 'https://example.com/apply-for-flight-crew'),
('Courier', 27, 16, 'Kampala', 'Full Time', 'Permanent', '2025-01-10', 'Courier role at DHL Express Uganda', 'https://example.com/apply-for-courier'),
('Medical Researcher', 28, 13, 'Kampala', 'Full Time', 'Permanent', '2025-01-12', 'Medical Researcher at Uganda Cancer Institute', 'https://example.com/apply-for-medical-researcher'),
('Broadcasting Technician', 29, 10, 'Kampala', 'Full Time', 'Permanent', '2025-01-14', 'Broadcasting Technician role at UBC', 'https://example.com/apply-for-broadcasting-technician'),
('Statistician', 30, 1, 'Kampala', 'Full Time', 'Permanent', '2025-01-16', 'Statistician at Uganda Bureau of Statistics', 'https://example.com/apply-for-statistician'),
('Telecommunications Officer', 31, 10, 'Kampala', 'Full Time', 'Permanent', '2025-01-18', 'Telecom Officer at MTN Group Limited', 'https://example.com/apply-for-telecom-officer'),
('Network Administrator', 32, 10, 'Kampala', 'Full Time', 'Permanent', '2025-01-20', 'Network Administrator at Uganda Telecom Limited', 'https://example.com/apply-for-network-administrator'),
('Petroleum Engineer', 33, 6, 'Hoima', 'Full Time', 'Contract', '2025-01-22', 'Petroleum Engineer role at Shell Uganda', 'https://example.com/apply-for-petroleum-engineer'),
('Loan Officer', 34, 1, 'Mbale', 'Full Time', 'Permanent', '2025-01-24', 'Loan Officer at Centenary Bank', 'https://example.com/apply-for-loan-officer'),
('Instructor', 35, 20, 'Kigumba', 'Full Time', 'Permanent', '2025-01-26', 'Instructor at Uganda Petroleum Institute Kigumba', 'https://example.com/apply-for-instructor'),
('Investment Officer', 36, 1, 'Kampala', 'Full Time', 'Permanent', '2025-01-28', 'Investment Officer at Uganda Development Bank Limited', 'https://example.com/apply-for-investment-officer'),
('Retail Associate', 37, 17, 'Kampala', 'Part Time', 'Temporary', '2025-01-30', 'Retail Associate at Bata Uganda Limited', 'https://example.com/apply-for-retail-associate'),
('Factory Worker', 38, 6, 'Kampala', 'Full Time', 'Permanent', '2025-02-01', 'Factory Worker at Mukwano Group of Companies', 'https://example.com/apply-for-factory-worker'),
('Postal Service Clerk', 39, 16, 'Kampala', 'Full Time', 'Permanent', '2025-02-03', 'Postal Clerk at Uganda Post Limited', 'https://example.com/apply-for-postal-service-clerk');
